<?php
// This file was automatically generated by the GamePanelX installer script.
$config['sql_host'] = 'localhost';
$config['sql_user'] = 'gamepanel';
$config['sql_pass'] = 'Sarasalapasaensucasa.';
$config['sql_db'] = 'gamepanel';
$config['encrypt_key'] = 'ADsystzdoairssjuDHrpFyiCsdxqpufepvCHduapugFcwgwrecFbAdDheqxtcAyrk';
?>
